### ISSUE TITLE
bin_prot: new release requires adaptation

### ISSUE THREAD

**Issue by avsm** [cryptosense/key-parsers#28]
See: https://github.com/ocaml/opam-repository/pull/8777 for an upper bound placed on ppx_bin_prot due to a compilation failure of key-parsers.0.7

The migration and fix is described in https://github.com/janestreet/bin_prot/issues/14 if you want to support the latest version of Core, which is being currently being tested for merge.  Existing releases will not break in stable opam, since the upper bound placed ensures that they use the old ppx_bin_prot.

**Comment by emillon** [comment]
Thanks for pointing out to that API, and for the report!
Just wrote a fix using it and it seems to work. :+1:
