### ISSUE TITLE
EC parameters are serialized as invalid JSON

### ISSUE THREAD

**Issue by emillon** [cryptosense/key-parsers#30]
EC parameters (and other parts) serialize Cstruct values directly as plain strings. This does not work for binary data, because [JSON strings represent Unicode data](https://tools.ietf.org/html/rfc7159#section-1).

The following program displays the problem:

```ocaml
  let ic = open_in path in
  let len = in_channel_length ic in
  let s = really_input_string ic len in
  close_in ic;
  Cstruct.of_string s

let () =
  "tests/keys/p256v1_explicit_param.der"
  |> read_cstruct
  |> Key_parsers.Asn1.EC.Params.decode
  |> Rresult.R.get_ok 
  |> Key_parsers.Asn1.EC.Params.to_yojson 
  |> Yojson.Safe.pretty_to_string 
  |> print_endline
```

This can be built as:

```
 % ocamlfind ocamlopt -package key-parsers -package yojson -package rresult -linkpkg dump.ml
 % ./a.out > out.json
 % python3 -mjson.tool out.json 
'utf-8' codec can't decode byte 0xff in position 180: invalid start byte
```

My suggestion is to use hex encoding prefixed with `0x`. A more space-efficient alternative is to use `base64` but this makes the output JSON less readable, and EC parameters are usually bounded in size anyway.

I'm happy to provide a patch if that's good with you.

Thanks!

**Comment by NathanReb** [comment]
Thanks for pointing that out! I'll fix it!

**Comment by emillon** [comment]
Thanks, you rock!
